name: xdem
channels:
  - conda-forge
dependencies:
  - python>=3
  - proj>=7.2
  - geopandas
  - ipython
  - numba
  - matplotlib
  - pdal
  - opencv
  - pytest
  - pyproj
  - rasterio
  - scipy
  - tqdm
  - scikit-image
  - scikit-learn
  - pip
  - proj-data
  - pip:
    - richdem
    - scikit-gstat
    - pytransform3d
    - https://github.com/GlacioHack/GeoUtils/tarball/master

variables:
        - PIP_NO_DEPS=1
