# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build-win

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        C:\Miniconda\condabin\conda.bat install -c conda-forge mamba -y
        C:\Miniconda\condabin\conda.bat env update --file environment.yml --name base
        C:\Miniconda\condabin\conda.bat init powershell
        C:\Miniconda\condabin\conda.bat activate base
        pip install git+https://github.com/GlacioHack/GeoUtils.git  --no-dependencies
        pip install sphinx numpydoc sphinx_rtd_theme sphinx_autodoc_typehints sphinxcontrib-programoutput
        pip install . --no-dependencies
    - name: Lint with flake8
      run: |
        C:\Miniconda\condabin\conda.bat init powershell
        C:\Miniconda\condabin\conda.bat activate base
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        C:\Miniconda\condabin\conda.bat init powershell
        C:\Miniconda\condabin\conda.bat activate base
        pytest -rA
